services:
  - type: web
    name: nb-delivery-vrp-demo
    env: python
    plan: free
    buildCommand: pip install -r demo/requirements.txt
    startCommand: cd demo && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_MAPS_API_KEY
        sync: false