services:
  - type: web
    name: nb-delivery-demo
    env: python
    rootDir: demo
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --workers=2 --threads=4 --timeout=120
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false
    plan: free
    autoDeploy: true

